### ISSUE TITLE
plauncher don't find the ui file.

### ISSUE THREAD

**Issue by ferrerjm** [javihernandez/ginfo-tweaks#1]
Hello,

I'm testing your tool to implement some user scripts, but the application fails to boot.

Evaluation system:
Guadalinfo GGv6 (karmic) updated.

As the problem occurs:
run plauncher

Output error:
  Traceback (most recent call last):
    File "/ usr / bin / plauncher", line 33, in <module>
      plauncher from import (
    File "/ usr/lib/pymodules/python2.6/plauncher/AboutPlauncherDialog.py", line 8, in <module>
    plauncher.helpers import from get_builder
   File "/ usr/lib/pymodules/python2.6/plauncher/helpers.py", line 15, in <module>
   plauncher.plauncherconfig import from get_data_file
   File "/ usr/lib/pymodules/python2.6/plauncher/plauncherconfig.py", line 22
  'plauncher', 'data')

Possible cause:
see plauncher fails because it does not assign routes. ui
on "/ usr/lib/pymodules/python2.6/plauncher/plauncherconfig.py"

get_data_file ui_filename = ('ui', '% s.ui'% (builder_file_name,))

and that comes from "/ usr/lib/pymodules/python2.6/plauncher/plauncherconfig.py" __ plauncher_data_directory__ = '/ usr / share / plauncher /'
                                                                'plauncher', 'data')
No missing '(' at the beginning?

also when using "/ usr/lib/python2.6/posixpath.py" said to be a tuple and ends with error.

tmp fix:
on "/usr/lib/pymodules/python2.6/plauncher/helpers.py"
# ui_filename = get_data_file('ui', '%s.ui' % (builder_file_name,))

ui_filename = "/usr/share/plauncher/ui/PlauncherWindow.ui"

on "/usr/lib/pymodules/python2.6/plauncher/plauncherconfig.py" 
**plauncher_data_directory** = ('/usr/share/plauncher/'
        'plauncher','data')

Excuse my English, gtranslater XD.

**Comment by javihernandez** [comment]
Hi! 

Thanks for the report!

I've still not looked at the error, but I'm wondering if you're installing ginfo-tweaks by using a debian package for that concrete distribution (Guadalinex Guadalinfo v6). ^^

If it is, I'll check first if I can run the application installed by using autotools, this is: ./autogen.sh && make && sudo make install
If it works, maybe the problem is coming from the debian package.

Anyway, I'll try to give it a try during this upcoming weekend. 

Best Regards!

PS: Don't worry about your english!! ;)

**Comment by ferrerjm** [comment]
Hello,

I have reviewed the github code and code of debian package, and I think that errors may come  from packaging.

I will talk to the maintainer of the package and inform you.

thank

**Comment by javihernandez** [comment]
Hi! 

I've just tried it, and I got the same error. If I compile the application and passing the --prefix=/usr option to ./autogen.sh , it works fine. So It's a bug, with an easy solution. Patches will be accepted! ;)

Thanks and,
regards!

**Comment by ferrerjm** [comment]
Hello

We have reviewed the process of creating the package and found that during the package creation, substitution on __ plauncher_data_directory__ fails:

"plauncherconfig.py"

  **plauncher_data_directory** = os.path.join (sys.prefix, 'share', \
         'plauncher', 'data')

we have looking for when / where is replaced and the check setup.py:

line = "% s = '% s' \ n"% (fields [0], prefix)

This replaces up "\" leaving, "'plauncher', 'data')" forgotten.

by avoiding the step in the line, corrected.

Thank you.
